### ISSUE TITLE
Doesnot show dynamic data

### ISSUE THREAD

**Issue by isaurssaurav** [shayanypn/ember-cli-highlighjs#1]
{{#highlight-code
  theme='atom-one-light'
  type='javascript'
  }}

{{gist.code}} // dynamic data like this doesnot showup 

{{/highlight-code}}

**Comment by aaronmw** [comment]
Can confirm. Makes this virtually useless to me and, probably, most everyone else in the world of Ember :(

**Comment by VincentMolinie** [comment]
I did create a dynamic version. I will make it an addon when I'll have some time ;)

**Comment by shayanypn** [comment]
@isaurssaurav @aaronmw this issue fixed here https://github.com/shayanypn/ember-cli-highlighjs/pull/2
